/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-variant': '#2d3449',
        'primary-container': '#8083ff',
        'surface-container': '#171f33',
        'on-surface-variant': '#c7c4d7',
        'surface-container-lowest': '#060e20',
        background: '#0b1326',
        tertiary: '#ffb783',
        'surface-container-low': '#131b2e',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        primary: '#c0c1ff',
        secondary: '#7bd0ff',
        'surface-dim': '#0b1326',
        'on-background': '#dae2fd',
        outline: '#908fa0',
        'on-surface': '#dae2fd',
        'outline-variant': '#464554',
        'on-primary': '#1000a9',
        surface: '#0b1326',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '24px',
        unit: '8px',
        'section-gap-desktop': '160px',
        gutter: '32px',
        'container-max': '1280px',
        'stack-gap': '24px',
        'section-gap-mobile': '80px',
      },
      fontFamily: {
        'display-xl': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '30px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
